In [1]:
from src.utils import (
    get_areas, 
    get_specimen_ids, 
    get_trials,
    get_units_count,
    get_summary_df,
    load_index
)

from src.neural_maps import (
    sim_corrected_source_pair, 
    pls_corrected_single_source_to_B
)

from src.mapping import (
    consistency_across_trials,
    interanimal_consistency_1v1,
    interanimal_consistency_pool
)

In [2]:
index_df = load_index("../allen-data-clean/PreprocData/index.csv")
summary_data_df = get_summary_df(index_df)
summary_data_df

Area  Number of Specimen IDs  Total Units  \
0   AL                       6          742   
1   AM                       7          586   
2   LM                       6          369   
3   PM                       5          386   
4   RL                       7          565   
5   V1                       8          748   

                Units per Specimen ID  
0         [85, 127, 184, 91, 166, 89]  
1       [70, 94, 71, 72, 70, 74, 135]  
2            [51, 53, 74, 56, 77, 58]  
3               [65, 115, 62, 90, 54]  
4       [76, 69, 67, 68, 79, 95, 111]  
5  [110, 102, 91, 85, 88, 93, 94, 85]

In [ ]:
import numpy as np

sus = get_trials(index_df, 718643567, area = 'RL')

np.isnan(sus).sum()

np.int64(2479)

In [12]:
# find NaN positions in `sus` (uses numpy and sus already defined)
nan_mask = np.isnan(sus)
nan_positions = np.argwhere(nan_mask)  # array of (i, j, k) indices

print(f"Found {len(nan_positions)} NaN positions in sus (shape {sus.shape}).")
print("First 20 NaN positions (dim0, dim1, dim2):")
print(nan_positions[:20])

# if you want a Python list of index tuples:
nan_positions_list = [tuple(idx) for idx in nan_positions]

Found 2479 NaN positions in sus (shape (50, 118, 67)).
First 20 NaN positions (dim0, dim1, dim2):
[[47 15  0]
 [47 15  1]
 [47 15  2]
 [47 15  3]
 [47 15  4]
 [47 15  5]
 [47 15  6]
 [47 15  7]
 [47 15  8]
 [47 15  9]
 [47 15 10]
 [47 15 11]
 [47 15 12]
 [47 15 13]
 [47 15 14]
 [47 15 15]
 [47 15 16]
 [47 15 17]
 [47 15 18]
 [47 15 19]]


## Comparing a mouse with itself across different areas

Fixed specimen id, different trials, for each area.

In [ ]:
# consistency_rsa = consistency_across_trials(index_df, sim_metric='RSA')
# consistency_cka = consistency_across_trials(index_df, sim_metric='CKA')
# consistency_cka

Area  Specimen ID      Mean       Std
0    AL    717038288  0.996077  0.018143
1    AL    738651054  0.999951  0.005381
2    AL    742714475  1.001408  0.006702
3    AL    745276236  1.005764  0.014167
4    AL    757329624  1.007141  0.015862
5    AL    775876828  1.002161  0.007823
6    AM    730756780  1.004552  0.011659
7    AM    730760270  1.013904  0.022345
8    AM    732548380  1.012569  0.027240
9    AM    734865738  1.003251  0.016786
10   AM    738651054  1.000644  0.005731
11   AM    742602892  1.006637  0.017305
12   AM    775876828  1.001294  0.017105
13   LM    723627604  1.005282  0.010984
14   LM    733457989  1.003841  0.011136
15   LM    745276236  1.002741  0.012674
16   LM    769360779  1.020946  0.035084
17   LM    775876828  1.001780  0.008355
18   LM    776061251  1.013801  0.022722
19   PM    717038288  1.005074  0.012885
20   PM    726170935  1.002822  0.012546
21   PM    730760270  1.012027  0.020109
22   PM    734865738  0.999464  0.005789
23   PM    738651054  1.000969  0.004820
24   RL    699733581  1.006777  0.015497
25   RL    716813543  1.020129  0.026695
26   RL    718643567       NaN       NaN
27   RL    722882755  1.025599  0.025810
28   RL    723627604  1.001758  0.007933
29   RL    732548380  1.009396  0.019571
30   RL    742714475  1.000011  0.003647
31   V1    717038288  1.003369  0.012564
32   V1    719828690  1.029445  0.030905
33   V1    726298253  1.001699  0.009741
34   V1    733457989  1.001534  0.006780
35   V1    738651054  1.000682  0.003959
36   V1    769360779  1.003447  0.010831
37   V1    775876828  1.003147  0.010974
38   V1    776061251  1.011456  0.021508

In [ ]:
# consistency_PLS = consistency_across_trials(index_df, sim_metric='PLS')
# consistency_PLS

# 1 vs 1 mapping: interanimal consistency

In [ ]:
# interanimal_consistency_1v1_df_rsa = interanimal_consistency_1v1(index_df, sim_metric='RSA')

# interanimal_consistency_1v1_df_rsa.groupby('Area')['Mean'].median()

Area
AL    0.525163
AM    0.443280
LM    0.298855
PM    0.388201
RL    0.378969
V1    0.432187
Name: Mean, dtype: float64

In [ ]:
# interanimal_consistency_1v1_df_cka = interanimal_consistency_1v1(index_df, sim_metric='CKA')

# interanimal_consistency_1v1_df_cka.groupby('Area')['Mean'].median()

Area
AL    0.447451
AM    0.438453
LM    0.207874
PM    0.344874
RL    0.299902
V1    0.410353
Name: Mean, dtype: float64

# Pooling version

In [3]:
iac_pool_rsa = interanimal_consistency_pool(index_df, sim_metric='RSA')
iac_pool_rsa.groupby('Area')['Mean'].median()

Area
AL    0.651665
AM    0.604958
LM    0.475808
PM    0.580446
RL         NaN
V1    0.624521
Name: Mean, dtype: float64

In [14]:
iac_pool_cka = interanimal_consistency_pool(index_df, sim_metric='CKA')
iac_pool_cka.groupby('Area')['Mean'].median()

Area
AL    0.558679
AM    0.600113
LM    0.394922
PM    0.510371
RL         NaN
V1    0.648063
Name: Mean, dtype: float64